### ISSUE TITLE
localNormalization？

### ISSUE THREAD

**Issue by xiexie123** [HuiZeng/BIQA_Toolbox#1]
hi
    I found localNormalization in getImdbLIVE.m or getImdbChalleng.m, and in src/localNormalization.m just   one line out_img = I; and other codes are disable. So there is no localNormalization in your experiments?

**Comment by HuiZeng** [comment]
hi!

Yes, there is no local normalization in my experiments. This function is
made available for potential usage.

2017-12-30 12:44 GMT+08:00 xiexie123 <notifications@github.com>:
