### ISSUE TITLE
CORNIA_Fv

### ISSUE THREAD

**Issue by TangZheng95** [HuiZeng/BIQA_Toolbox#4]

**Comment by HuiZeng** [comment]
To run evaluating_existing_methods.m, you need to download the supported_methods first. 
You can find the download links in my introduction.

**Comment by TangZheng95** [comment]
> To run evaluating_existing_methods.m, you need to download the supported_methods first.
> You can find the download links in my introduction.

Thanks! I had found this question in  the early morning so I closed this issue.
