### ISSUE TITLE
code for 《BLIND IMAGE QUALITY ASSESSMENT WITH A PROBABILISTIC QUALITY REPRESENTATION》

### ISSUE THREAD

**Issue by shenguquanxin** [HuiZeng/BIQA_Toolbox#5]
您好，请问什么时候开源这篇文章代码

**Comment by HuiZeng** [comment]
什么意思？这个不就是代码吗？

**Comment by shenguquanxin** [comment]
> 什么意思？这个不就是代码吗？

哦不好意思，我刚才以为只有《A Probabilistic Quality Representation Approach to Deep Blind Image Quality Prediction》这篇文章的源码。看了下tools里面的代码，是有ICIP18这篇的。多谢~
